### ISSUE TITLE
fluentcms-link New Logo Design

### ISSUE THREAD

**Issue by batarian71** [bashu/fluentcms-link#1]
Hi, for help you, I designed a logo for the fluentcms-link plugin. If you like it, I'll send you the files as pr. If you have something you want to add or remove, you can say it.

**Comment by bashu** [comment]
@batarian71 please do

**Comment by batarian71** [comment]
![whatsapp image 2018-04-28 at 19 16 30](https://user-images.githubusercontent.com/36008612/39398802-d8dc9fc8-4b1b-11e8-8c80-188de35c7c9d.jpeg)

**Comment by batarian71** [comment]
would you prefer one of these? or Is there anything else you want?

**Comment by bashu** [comment]
@batarian71 thanks for contribution, at least there was an attempt...
